name: .NET

on:
  push:
    branches: [ TestHeroku ]
  pull_request:
    branches: [ TestHeroku ]

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        APP_NAME: ${{ 'ressources-relationnelle' }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Publish
      run: dotnet publish -c Release -o src/publish
    - name: Build docker image
      run: |
        docker build . -t ${{ env.APP_NAME }} -f Dockerfile
        docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
        heroku container:push web -a $APP_NAME
        heroku container:release web -a $APP_NAME
